//! Differential parity test: the Rust config schema against govox-py's.
//!
//! `corpus/config-defaults.json` is generated by running the **pinned**
//! govox-py (see `REFERENCE` and `tools/parity-gen/config_dump.py`), with an
//! empty `XDG_CONFIG_HOME` and no `GOVOX__` variables, so it is a property of
//! that commit rather than of whoever generated it.
//!
//! This is the M2 harness pattern in miniature, and it catches the failure that
//! a schema port is most prone to: a key that exists upstream and was missed
//! here, or a default that was transcribed slightly wrong. Neither shows up in
//! a hand-written assertion, because you only assert what you remembered.
//!
//! Regenerate deliberately, and read the diff:
//!
//! ```console
//! $ ./tools/parity-gen/pinned-source.sh
//! $ PYTHONPATH=tools/parity-gen/.parity-src/src <interpreter> \
//!     tools/parity-gen/config_dump.py > corpus/config-defaults.json
//! ```

use govox_core::config::{Config, Environment};

const REFERENCE: &str = include_str!("../../../corpus/config-defaults.json");

/// Config keys `govox-rs` has and `govox-py` does not.
///
/// Every entry is a deliberate divergence with a matching row in
/// `docs/parity.md`. The list exists so that an addition has to be *declared*:
/// tolerating unknown extra keys in general would hide the case this test is
/// really for, which is a key that drifted apart by accident.
///
/// - `recognition.gpu_device` — which GPU to run on. `govox-py` cannot select
///   one: CTranslate2 accepts a device index but faster-whisper does not expose
///   it, so the reference always takes whatever the driver enumerates first.
const RUST_ONLY_KEYS: &[&str] = &["recognition.gpu_device"];

/// Compare two JSON values, collecting every difference as a dotted path.
///
/// Reports *all* differences rather than the first, because a schema drift
/// usually shows up as several keys at once and fixing them one test-run at a
/// time is miserable.
fn diff(a: &serde_json::Value, b: &serde_json::Value, path: &str, out: &mut Vec<String>) {
    use serde_json::Value;
    match (a, b) {
        (Value::Object(left), Value::Object(right)) => {
            let mut keys: Vec<&String> = left.keys().chain(right.keys()).collect();
            keys.sort_unstable();
            keys.dedup();
            for key in keys {
                let child = if path.is_empty() {
                    key.clone()
                } else {
                    format!("{path}.{key}")
                };
                match (left.get(key), right.get(key)) {
                    (Some(l), Some(r)) => diff(l, r, &child, out),
                    (Some(_), None) => out.push(format!("{child}: only in rust")),
                    (None, Some(_)) => out.push(format!("{child}: MISSING from rust")),
                    (None, None) => unreachable!(),
                }
            }
        }
        (Value::Number(left), Value::Number(right)) => {
            // 45 and 45.0 are the same configured value; pydantic renders a
            // float field holding a whole number as 45.0, serde as 45.0 too,
            // but an int field differs in type. Compare numerically.
            let (l, r) = (left.as_f64(), right.as_f64());
            if l != r {
                out.push(format!("{path}: rust={left} python={right}"));
            }
        }
        (left, right) => {
            if left != right {
                out.push(format!("{path}: rust={left} python={right}"));
            }
        }
    }
}

/// Guard the guard.
///
/// A comparison test that silently compares nothing still passes, and this one
/// is the only thing standing between a mistranscribed default and a silent
/// behaviour change. So: plant known drift and require it to be caught.
#[test]
fn the_diff_detects_drift() {
    let base: serde_json::Value = serde_json::from_str(REFERENCE).unwrap();

    // A changed value.
    let mut changed = base.clone();
    changed["recognition"]["model"] = serde_json::Value::String("tiny".into());
    let mut found = Vec::new();
    diff(&changed, &base, "", &mut found);
    assert_eq!(found.len(), 1, "changed value: {found:?}");
    assert!(found[0].starts_with("recognition.model:"), "{found:?}");

    // A key missing from the Rust side — the drift that matters most, because
    // it is what an upstream addition looks like.
    let mut missing = base.clone();
    missing["recognition"]
        .as_object_mut()
        .unwrap()
        .remove("model");
    let mut found = Vec::new();
    diff(&missing, &base, "", &mut found);
    assert_eq!(found, ["recognition.model: MISSING from rust"], "{found:?}");

    // A key only on the Rust side.
    let mut extra = base.clone();
    extra["recognition"]
        .as_object_mut()
        .unwrap()
        .insert("invented".into(), serde_json::Value::Bool(true));
    let mut found = Vec::new();
    diff(&extra, &base, "", &mut found);
    assert_eq!(found, ["recognition.invented: only in rust"], "{found:?}");

    // And identity really is quiet.
    let mut found = Vec::new();
    diff(&base, &base, "", &mut found);
    assert!(found.is_empty(), "{found:?}");
}

#[test]
fn rust_defaults_match_the_pinned_python_defaults() {
    // Empty environment: no XDG_CONFIG_HOME, no HOME, so no user config layer
    // and no overrides — the same conditions the generator ran under.
    let config = Config::load_from(None, &Environment::default())
        .expect("the shipped default.toml must load on its own");

    let rust: serde_json::Value = serde_json::to_value(&config).expect("config serialises to JSON");
    let python: serde_json::Value =
        serde_json::from_str(REFERENCE).expect("corpus/config-defaults.json is valid JSON");

    let mut differences = Vec::new();
    diff(&rust, &python, "", &mut differences);

    // Declared additions are removed here rather than skipped in , so a
    // key that stops being an addition — because it was added upstream, or
    // renamed here — resurfaces as a failure instead of staying invisible.
    differences.retain(|d| {
        !RUST_ONLY_KEYS
            .iter()
            .any(|key| d == &format!("{key}: only in rust"))
    });

    assert!(
        differences.is_empty(),
        "Rust config diverges from govox-py @ REFERENCE in {} place(s):\n  {}",
        differences.len(),
        differences.join("\n  ")
    );
}

#[test]
fn every_declared_addition_is_really_an_addition() {
    // Guard the allowlist. An entry that no longer corresponds to a real
    // Rust-only key is dead weight that would mask the next genuine drift.
    let config = Config::load_from(None, &Environment::default()).expect("defaults load");
    let rust: serde_json::Value = serde_json::to_value(&config).expect("serialises");
    let python: serde_json::Value = serde_json::from_str(REFERENCE).expect("valid JSON");

    let mut differences = Vec::new();
    diff(&rust, &python, "", &mut differences);

    for key in RUST_ONLY_KEYS {
        assert!(
            differences.contains(&format!("{key}: only in rust")),
            "{key} is on the allowlist but is not a Rust-only key; remove it"
        );
    }
}
